/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
// This file is a placeholder. Replace with your actual Amplify configuration from 'amplify pull' or AWS Console.
// Update the following values with CloudFormation outputs:
// - aws_user_pools_id: Use CloudFormation output 'UserPoolId'
// - aws_user_pools_web_client_id: Use CloudFormation output 'UserPoolClientId'

/* eslint-disable */
export default {
  "aws_project_region": "us-east-1",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_XXXXXXXXX", // Replace with CloudFormation output: UserPoolId
  "aws_user_pools_web_client_id": "XXXXXXXXXXXXXXXXXXXXX", // Replace with CloudFormation output: UserPoolClientId
  "oauth": {},
  "aws_cognito_username_attributes": [
    "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
    "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
    "SMS"
  ],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
    "EMAIL"
  ],
  "aws_appsync_graphqlEndpoint": "https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-xxxxxxxxxxxxxxxxxxxxxxxxxx"
};